name: 'Ubuntu CMake Workflow'
description: 'Run a CMake workflow preset for Ubuntu builds'
inputs:
  cmake_workflow:
    description: 'The cmake workflow to use.'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Run CMake workflow
      run: |
        cmake --workflow --preset ${{ inputs.cmake_workflow }}
      shell: bash