name: linux

on:
  push:
    branches:
      - main
      - develop
      - 'develop-*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cxx: [ g++-11, clang++-14 ]
        build_type: [ Debug, Release ]
        std: [ 11, 14, 17, 20 ]
        include:
          - cxx: clang++-14
            cxxflags: -stdlib=libc++
            cmd_install: sudo apt update && sudo apt install clang-14 libc++-14-dev libc++abi-14-dev ninja-build
          - cxx: g++-11
            cmd_install: sudo apt update && sudo apt install g++-11 ninja-build
          - shared: -DBUILD_SHARED_LIBS=ON

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: |
          ${{ matrix.cmd_install }}

      - name: Configure
        env:
          CXX: ${{matrix.cxx}}
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{matrix.shared}} \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} \
                -DCMAKE_CXX_FLAGS="${{ matrix.cxxflags }}" \
                $GITHUB_WORKSPACE

      - name: Build
        run: |
          threads=`nproc`
          cmake --build . --config ${{matrix.build_type}} --parallel $threads

      - name: Test
        run: ctest -C ${{matrix.build_type}}
        env:
          CTEST_OUTPUT_ON_FAILURE: True

      - name: Package Installation Test
        run: |
          cmake --build . --config ${{matrix.build_type}} --target test_install
