name: Ubuntu Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ubuntu-build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-build-steps
        with:
          cmake_workflow: workflow-test-gcc-debug

  ubuntu-build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-build-steps
        with:
          cmake_workflow: workflow-test-gcc-release